#read the read.txt before run the code
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets
import pandas as pd
import numpy as np
import recommendations

movies=pd.read_csv("movie4.csv")


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 768)
        MainWindow.setMinimumSize(QtCore.QSize(1366, 768))
        MainWindow.setStyleSheet("color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topbar = QtWidgets.QFrame(self.centralwidget)
        self.topbar.setMaximumSize(QtCore.QSize(16777215, 60))
        self.topbar.setStyleSheet("background-color: rgb(255, 66, 79);")
        self.topbar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topbar.setObjectName("topbar")
        self.searchbar = QtWidgets.QLineEdit(self.topbar)
        self.searchbar.setGeometry(QtCore.QRect(1175, 13, 171, 40))
        self.searchbar.setMaximumSize(QtCore.QSize(272, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.searchbar.setFont(font)
        self.searchbar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.searchbar.setAutoFillBackground(False)
        self.searchbar.setStyleSheet("background-image: url(:/searchimage/baseline_search_white_18dp.png);\n"
"background-repeat:repeat;\n"
"")
        self.searchbar.setInputMask("")
        self.searchbar.setFrame(False)
        self.searchbar.setObjectName("searchbar")
        self.frame = QtWidgets.QFrame(self.topbar)
        self.frame.setGeometry(QtCore.QRect(-1, -1, 221, 60))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame.setStyleSheet("background-color: rgb(248, 55, 69);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 211, 51))
        self.label_3.setMaximumSize(QtCore.QSize(221, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setStyleSheet("")
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(16, 2, 51, 61))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("../../../Downloads/logo_free-file.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.topbar)
        self.context = QtWidgets.QFrame(self.centralwidget)
        self.context.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.context.setStyleSheet("background-color: rgb(34, 43, 49);")
        self.context.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.context.setFrameShadow(QtWidgets.QFrame.Raised)
        self.context.setObjectName("context")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.context)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.context)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 221, 16777215))
        self.frame_3.setStyleSheet("background-color: rgb(25, 28, 31);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_3)
        self.scrollArea.setGeometry(QtCore.QRect(0, 70, 221, 561))
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 221, 561))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 221, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButton.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setTabletTracking(False)
        self.pushButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setStyleSheet("")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("home-5-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(32, 32))
        self.pushButton.setCheckable(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 60, 221, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButton_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setTabletTracking(False)
        self.pushButton_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_2.setText("Movies")
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_4.setGeometry(QtCore.QRect(0, 450, 221, 3))
        self.frame_4.setStyleSheet("background-color: rgb(34, 43, 49);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.About = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.About.setGeometry(QtCore.QRect(0, 460, 221, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.About.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.About.setFont(font)
        self.About.setTabletTracking(False)
        self.About.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.About.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.About.setText("About")
        self.About.setCheckable(False)
        self.About.setAutoDefault(False)
        self.About.setDefault(False)
        self.About.setFlat(False)
        self.About.setObjectName("About")
        self.pushButton_15 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_15.setGeometry(QtCore.QRect(0, 120, 221, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 28, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButton_15.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setTabletTracking(False)
        self.pushButton_15.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_15.setText("Discover")
        self.pushButton_15.setCheckable(False)
        self.pushButton_15.setFlat(False)
        self.pushButton_15.setObjectName("pushButton_15")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget = QtWidgets.QTabWidget(self.frame_2)
        self.tabWidget.setGeometry(QtCore.QRect(220, -20, 16777215, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.Home = QtWidgets.QWidget()
        self.Home.setObjectName("Home")
        self.label_66 = QtWidgets.QLabel(self.Home)
        self.label_66.setGeometry(QtCore.QRect(40, 70, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_66.setFont(font)
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(self.Home)
        self.label_67.setGeometry(QtCore.QRect(690, 510, 191, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_67.setFont(font)
        self.label_67.setStyleSheet("color: rgb(107, 134, 153);")
        self.label_67.setObjectName("label_67")
        self.label_68 = QtWidgets.QLabel(self.Home)
        self.label_68.setGeometry(QtCore.QRect(250, 510, 171, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_68.setFont(font)
        self.label_68.setStyleSheet("color: rgb(107, 134, 153);")
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QLabel(self.Home)
        self.label_69.setGeometry(QtCore.QRect(690, 490, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_69.setFont(font)
        self.label_69.setObjectName("label_69")
        self.label_70 = QtWidgets.QLabel(self.Home)
        self.label_70.setGeometry(QtCore.QRect(910, 490, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_70.setFont(font)
        self.label_70.setObjectName("label_70")
        self.label_71 = QtWidgets.QLabel(self.Home)
        self.label_71.setGeometry(QtCore.QRect(470, 510, 181, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_71.setFont(font)
        self.label_71.setStyleSheet("color: rgb(107, 134, 153);")
        self.label_71.setObjectName("label_71")
        self.label_72 = QtWidgets.QLabel(self.Home)
        self.label_72.setGeometry(QtCore.QRect(910, 510, 171, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_72.setFont(font)
        self.label_72.setStyleSheet("color: rgb(107, 134, 153);")
        self.label_72.setObjectName("label_72")
        self.label_73 = QtWidgets.QLabel(self.Home)
        self.label_73.setGeometry(QtCore.QRect(30, 490, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_73.setFont(font)
        self.label_73.setObjectName("label_73")
        self.label_74 = QtWidgets.QLabel(self.Home)
        self.label_74.setGeometry(QtCore.QRect(30, 510, 191, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_74.setFont(font)
        self.label_74.setStyleSheet("color: rgb(107, 134, 153);")
        self.label_74.setObjectName("label_74")
        self.frame_51 = QtWidgets.QFrame(self.Home)
        self.frame_51.setGeometry(QtCore.QRect(100, 150, 51, 31))
        self.frame_51.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(255, 172, 7);\n"
"")
        self.frame_51.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_51.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_51.setObjectName("frame_51")
        self.label_75 = QtWidgets.QLabel(self.frame_51)
        self.label_75.setGeometry(QtCore.QRect(5, 4, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_75.setFont(font)
        self.label_75.setAlignment(QtCore.Qt.AlignCenter)
        self.label_75.setObjectName("label_75")
        self.label_76 = QtWidgets.QLabel(self.Home)
        self.label_76.setGeometry(QtCore.QRect(470, 490, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_76.setFont(font)
        self.label_76.setObjectName("label_76")
        self.label_77 = QtWidgets.QLabel(self.Home)
        self.label_77.setGeometry(QtCore.QRect(240, 490, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_77.setFont(font)
        self.label_77.setObjectName("label_77")
        self.frame_53 = QtWidgets.QFrame(self.Home)
        self.frame_53.setGeometry(QtCore.QRect(540, 150, 51, 31))
        self.frame_53.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(255, 172, 7);\n"
"")
        self.frame_53.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_53.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_53.setObjectName("frame_53")
        self.label_78 = QtWidgets.QLabel(self.frame_53)
        self.label_78.setGeometry(QtCore.QRect(5, 4, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_78.setFont(font)
        self.label_78.setAlignment(QtCore.Qt.AlignCenter)
        self.label_78.setObjectName("label_78")
        self.frame_54 = QtWidgets.QFrame(self.Home)
        self.frame_54.setGeometry(QtCore.QRect(980, 150, 51, 31))
        self.frame_54.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(255, 172, 7);\n"
"")
        self.frame_54.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_54.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_54.setObjectName("frame_54")
        self.label_79 = QtWidgets.QLabel(self.frame_54)
        self.label_79.setGeometry(QtCore.QRect(5, 4, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_79.setFont(font)
        self.label_79.setAlignment(QtCore.Qt.AlignCenter)
        self.label_79.setObjectName("label_79")
        self.frame_55 = QtWidgets.QFrame(self.Home)
        self.frame_55.setGeometry(QtCore.QRect(760, 150, 51, 31))
        self.frame_55.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(255, 172, 7);\n"
"")
        self.frame_55.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_55.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_55.setObjectName("frame_55")
        self.label_80 = QtWidgets.QLabel(self.frame_55)
        self.label_80.setGeometry(QtCore.QRect(5, 4, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_80.setFont(font)
        self.label_80.setAlignment(QtCore.Qt.AlignCenter)
        self.label_80.setObjectName("label_80")
        self.frame_56 = QtWidgets.QFrame(self.Home)
        self.frame_56.setGeometry(QtCore.QRect(320, 150, 51, 31))
        self.frame_56.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(255, 172, 7);\n"
"")
        self.frame_56.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_56.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_56.setObjectName("frame_56")
        self.label_81 = QtWidgets.QLabel(self.frame_56)
        self.label_81.setGeometry(QtCore.QRect(5, 4, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_81.setFont(font)
        self.label_81.setAlignment(QtCore.Qt.AlignCenter)
        self.label_81.setObjectName("label_81")
        self.label_8 = QtWidgets.QLabel(self.Home)
        self.label_8.setGeometry(QtCore.QRect(30, 170, 191, 311))
        self.label_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("ForrestGumpPoster.jpg"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.Home)
        self.label_9.setGeometry(QtCore.QRect(250, 170, 191, 311))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("The_Shawshank_Redemption_pôster.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.Home)
        self.label_10.setGeometry(QtCore.QRect(470, 170, 191, 311))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("230px-Pulp_Fiction_cover.jpg"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.Home)
        self.label_11.setGeometry(QtCore.QRect(690, 170, 191, 311))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("Silence_of_the_lambs.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.Home)
        self.label_12.setGeometry(QtCore.QRect(910, 170, 191, 311))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("The_Matrix_Poster.jpg"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.pushButton_17 = QtWidgets.QPushButton(self.Home)
        self.pushButton_17.setGeometry(QtCore.QRect(30, 440, 32, 32))
        self.pushButton_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_17.setAutoFillBackground(False)
        self.pushButton_17.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_17.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../Downloads/video-play-3-32 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_17.setIcon(icon1)
        self.pushButton_17.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_17.setAutoExclusive(False)
        self.pushButton_17.setAutoDefault(False)
        self.pushButton_17.setDefault(False)
        self.pushButton_17.setFlat(True)
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.Home)
        self.pushButton_18.setGeometry(QtCore.QRect(260, 440, 32, 32))
        self.pushButton_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_18.setAutoFillBackground(False)
        self.pushButton_18.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_18.setText("")
        self.pushButton_18.setIcon(icon1)
        self.pushButton_18.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_18.setAutoExclusive(False)
        self.pushButton_18.setAutoDefault(False)
        self.pushButton_18.setDefault(False)
        self.pushButton_18.setFlat(True)
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.Home)
        self.pushButton_19.setGeometry(QtCore.QRect(480, 440, 32, 32))
        self.pushButton_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_19.setAutoFillBackground(False)
        self.pushButton_19.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_19.setText("")
        self.pushButton_19.setIcon(icon1)
        self.pushButton_19.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_19.setAutoExclusive(False)
        self.pushButton_19.setAutoDefault(False)
        self.pushButton_19.setDefault(False)
        self.pushButton_19.setFlat(True)
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.Home)
        self.pushButton_20.setGeometry(QtCore.QRect(700, 440, 32, 32))
        self.pushButton_20.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_20.setAutoFillBackground(False)
        self.pushButton_20.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_20.setText("")
        self.pushButton_20.setIcon(icon1)
        self.pushButton_20.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_20.setAutoExclusive(False)
        self.pushButton_20.setAutoDefault(False)
        self.pushButton_20.setDefault(False)
        self.pushButton_20.setFlat(True)
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.Home)
        self.pushButton_21.setGeometry(QtCore.QRect(920, 440, 32, 32))
        self.pushButton_21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_21.setAutoFillBackground(False)
        self.pushButton_21.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_21.setText("")
        self.pushButton_21.setIcon(icon1)
        self.pushButton_21.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_21.setAutoExclusive(False)
        self.pushButton_21.setAutoDefault(False)
        self.pushButton_21.setDefault(False)
        self.pushButton_21.setFlat(True)
        self.pushButton_21.setObjectName("pushButton_21")
        self.label_66.raise_()
        self.label_67.raise_()
        self.label_68.raise_()
        self.label_69.raise_()
        self.label_70.raise_()
        self.label_71.raise_()
        self.label_72.raise_()
        self.label_73.raise_()
        self.label_74.raise_()
        self.label_76.raise_()
        self.label_77.raise_()
        self.label_8.raise_()
        self.frame_51.raise_()
        self.label_9.raise_()
        self.frame_56.raise_()
        self.label_10.raise_()
        self.frame_53.raise_()
        self.label_11.raise_()
        self.frame_55.raise_()
        self.label_12.raise_()
        self.frame_54.raise_()
        self.pushButton_17.raise_()
        self.pushButton_18.raise_()
        self.pushButton_19.raise_()
        self.pushButton_20.raise_()
        self.pushButton_21.raise_()
        self.tabWidget.addTab(self.Home, "")
        self.Actiontab = QtWidgets.QWidget()
        self.Actiontab.setObjectName("Actiontab")
        self.Movies = QtWidgets.QComboBox(self.Actiontab)
        self.Movies.setGeometry(QtCore.QRect(40, 100, 451, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.Movies.setFont(font)
        self.Movies.setEditable(True)
        self.Movies.setObjectName("Movies")
        self.Recomendation = QtWidgets.QLabel(self.Actiontab)
        self.Recomendation.setGeometry(QtCore.QRect(720, 40, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Recomendation.setFont(font)
        self.Recomendation.setObjectName("Recomendation")
        self.pushButton_3 = QtWidgets.QPushButton(self.Actiontab)
        self.pushButton_3.setGeometry(QtCore.QRect(490, 100, 81, 41))
        self.pushButton_3.setDefault(False)
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.listWidget = QtWidgets.QListWidget(self.Actiontab)
        self.listWidget.setGeometry(QtCore.QRect(720, 100, 321, 111))
        self.listWidget.setObjectName("listWidget")
        self.frame_52 = QtWidgets.QFrame(self.Actiontab)
        self.frame_52.setGeometry(QtCore.QRect(157, 280, 51, 31))
        self.frame_52.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(255, 172, 7);\n"
"")
        self.frame_52.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_52.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_52.setObjectName("frame_52")
        self.rating = QtWidgets.QLabel(self.frame_52)
        self.rating.setGeometry(QtCore.QRect(5, 4, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.rating.setFont(font)
        self.rating.setText("")
        self.rating.setAlignment(QtCore.Qt.AlignCenter)
        self.rating.setObjectName("rating")
        self.label_6 = QtWidgets.QLabel(self.Actiontab)
        self.label_6.setGeometry(QtCore.QRect(20, 300, 321, 111))
        self.label_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("Captura de ecrã 2020-05-28, às 11.18.43.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.genrer = QtWidgets.QLabel(self.Actiontab)
        self.genrer.setGeometry(QtCore.QRect(20, 430, 321, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.genrer.setFont(font)
        self.genrer.setStyleSheet("color: rgb(107, 134, 153);")
        self.genrer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.genrer.setText("")
        self.genrer.setObjectName("genrer")
        self.titler = QtWidgets.QLabel(self.Actiontab)
        self.titler.setGeometry(QtCore.QRect(20, 410, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.titler.setFont(font)
        self.titler.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.titler.setText("")
        self.titler.setObjectName("titler")
        self.Recomendation_2 = QtWidgets.QLabel(self.Actiontab)
        self.Recomendation_2.setGeometry(QtCore.QRect(30, 220, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Recomendation_2.setFont(font)
        self.Recomendation_2.setObjectName("Recomendation_2")
        self.titler4 = QtWidgets.QLabel(self.Actiontab)
        self.titler4.setGeometry(QtCore.QRect(20, 590, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.titler4.setFont(font)
        self.titler4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.titler4.setText("")
        self.titler4.setObjectName("titler4")
        self.genrer4 = QtWidgets.QLabel(self.Actiontab)
        self.genrer4.setGeometry(QtCore.QRect(20, 610, 321, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.genrer4.setFont(font)
        self.genrer4.setStyleSheet("color: rgb(107, 134, 153);")
        self.genrer4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.genrer4.setText("")
        self.genrer4.setObjectName("genrer4")
        self.label_14 = QtWidgets.QLabel(self.Actiontab)
        self.label_14.setGeometry(QtCore.QRect(20, 480, 321, 111))
        self.label_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("Captura de ecrã 2020-05-28, às 11.18.43.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.frame_57 = QtWidgets.QFrame(self.Actiontab)
        self.frame_57.setGeometry(QtCore.QRect(157, 460, 51, 31))
        self.frame_57.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(255, 172, 7);\n"
"")
        self.frame_57.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_57.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_57.setObjectName("frame_57")
        self.rating4 = QtWidgets.QLabel(self.frame_57)
        self.rating4.setGeometry(QtCore.QRect(5, 4, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.rating4.setFont(font)
        self.rating4.setText("")
        self.rating4.setAlignment(QtCore.Qt.AlignCenter)
        self.rating4.setObjectName("rating4")
        self.titler2 = QtWidgets.QLabel(self.Actiontab)
        self.titler2.setGeometry(QtCore.QRect(370, 410, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.titler2.setFont(font)
        self.titler2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.titler2.setText("")
        self.titler2.setObjectName("titler2")
        self.genrer2 = QtWidgets.QLabel(self.Actiontab)
        self.genrer2.setGeometry(QtCore.QRect(370, 430, 321, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.genrer2.setFont(font)
        self.genrer2.setStyleSheet("color: rgb(107, 134, 153);")
        self.genrer2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.genrer2.setText("")
        self.genrer2.setObjectName("genrer2")
        self.genrer5 = QtWidgets.QLabel(self.Actiontab)
        self.genrer5.setGeometry(QtCore.QRect(370, 610, 321, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.genrer5.setFont(font)
        self.genrer5.setStyleSheet("color: rgb(107, 134, 153);")
        self.genrer5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.genrer5.setText("")
        self.genrer5.setObjectName("genrer5")
        self.frame_58 = QtWidgets.QFrame(self.Actiontab)
        self.frame_58.setGeometry(QtCore.QRect(507, 460, 51, 31))
        self.frame_58.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(255, 172, 7);\n"
"")
        self.frame_58.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_58.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_58.setObjectName("frame_58")
        self.rating5 = QtWidgets.QLabel(self.frame_58)
        self.rating5.setGeometry(QtCore.QRect(5, 4, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.rating5.setFont(font)
        self.rating5.setText("")
        self.rating5.setAlignment(QtCore.Qt.AlignCenter)
        self.rating5.setObjectName("rating5")
        self.titler5 = QtWidgets.QLabel(self.Actiontab)
        self.titler5.setGeometry(QtCore.QRect(370, 590, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.titler5.setFont(font)
        self.titler5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.titler5.setText("")
        self.titler5.setObjectName("titler5")
        self.label_15 = QtWidgets.QLabel(self.Actiontab)
        self.label_15.setGeometry(QtCore.QRect(370, 300, 321, 111))
        self.label_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("Captura de ecrã 2020-05-28, às 11.18.43.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.Actiontab)
        self.label_16.setGeometry(QtCore.QRect(370, 480, 321, 111))
        self.label_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("Captura de ecrã 2020-05-28, às 11.18.43.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.frame_59 = QtWidgets.QFrame(self.Actiontab)
        self.frame_59.setGeometry(QtCore.QRect(507, 280, 51, 31))
        self.frame_59.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(255, 172, 7);\n"
"")
        self.frame_59.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_59.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_59.setObjectName("frame_59")
        self.rating2 = QtWidgets.QLabel(self.frame_59)
        self.rating2.setGeometry(QtCore.QRect(5, 4, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.rating2.setFont(font)
        self.rating2.setText("")
        self.rating2.setAlignment(QtCore.Qt.AlignCenter)
        self.rating2.setObjectName("rating2")
        self.titler3 = QtWidgets.QLabel(self.Actiontab)
        self.titler3.setGeometry(QtCore.QRect(720, 410, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.titler3.setFont(font)
        self.titler3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.titler3.setText("")
        self.titler3.setObjectName("titler3")
        self.genrer3 = QtWidgets.QLabel(self.Actiontab)
        self.genrer3.setGeometry(QtCore.QRect(720, 430, 321, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.genrer3.setFont(font)
        self.genrer3.setStyleSheet("color: rgb(107, 134, 153);")
        self.genrer3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.genrer3.setText("")
        self.genrer3.setObjectName("genrer3")
        self.label_17 = QtWidgets.QLabel(self.Actiontab)
        self.label_17.setGeometry(QtCore.QRect(720, 300, 321, 111))
        self.label_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("Captura de ecrã 2020-05-28, às 11.18.43.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.frame_60 = QtWidgets.QFrame(self.Actiontab)
        self.frame_60.setGeometry(QtCore.QRect(857, 280, 51, 31))
        self.frame_60.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(255, 172, 7);\n"
"")
        self.frame_60.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_60.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_60.setObjectName("frame_60")
        self.rating3 = QtWidgets.QLabel(self.frame_60)
        self.rating3.setGeometry(QtCore.QRect(5, 4, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.rating3.setFont(font)
        self.rating3.setText("")
        self.rating3.setAlignment(QtCore.Qt.AlignCenter)
        self.rating3.setObjectName("rating3")
        self.pushButton_4 = QtWidgets.QPushButton(self.Actiontab)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 370, 32, 32))
        self.pushButton_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_4.setAutoFillBackground(True)
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_4.setText("")
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_4.setAutoExclusive(False)
        self.pushButton_4.setAutoDefault(False)
        self.pushButton_4.setDefault(False)
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.Actiontab)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 550, 32, 32))
        self.pushButton_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_5.setAutoFillBackground(False)
        self.pushButton_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_5.setText("")
        self.pushButton_5.setIcon(icon1)
        self.pushButton_5.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_5.setAutoExclusive(False)
        self.pushButton_5.setAutoDefault(False)
        self.pushButton_5.setDefault(False)
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.Actiontab)
        self.pushButton_6.setGeometry(QtCore.QRect(380, 370, 32, 32))
        self.pushButton_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_6.setAutoFillBackground(False)
        self.pushButton_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_6.setText("")
        self.pushButton_6.setIcon(icon1)
        self.pushButton_6.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_6.setAutoExclusive(False)
        self.pushButton_6.setAutoDefault(False)
        self.pushButton_6.setDefault(False)
        self.pushButton_6.setFlat(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.Actiontab)
        self.pushButton_7.setGeometry(QtCore.QRect(380, 550, 32, 32))
        self.pushButton_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_7.setAutoFillBackground(False)
        self.pushButton_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_7.setText("")
        self.pushButton_7.setIcon(icon1)
        self.pushButton_7.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_7.setAutoExclusive(False)
        self.pushButton_7.setAutoDefault(False)
        self.pushButton_7.setDefault(False)
        self.pushButton_7.setFlat(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.Actiontab)
        self.pushButton_8.setGeometry(QtCore.QRect(730, 370, 32, 32))
        self.pushButton_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_8.setAutoFillBackground(False)
        self.pushButton_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_8.setText("")
        self.pushButton_8.setIcon(icon1)
        self.pushButton_8.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_8.setAutoExclusive(False)
        self.pushButton_8.setAutoDefault(False)
        self.pushButton_8.setDefault(False)
        self.pushButton_8.setFlat(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.Movies.raise_()
        self.Recomendation.raise_()
        self.pushButton_3.raise_()
        self.listWidget.raise_()
        self.label_6.raise_()
        self.frame_52.raise_()
        self.genrer.raise_()
        self.titler.raise_()
        self.Recomendation_2.raise_()
        self.titler4.raise_()
        self.genrer4.raise_()
        self.label_14.raise_()
        self.frame_57.raise_()
        self.titler2.raise_()
        self.genrer2.raise_()
        self.genrer5.raise_()
        self.titler5.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.frame_59.raise_()
        self.frame_58.raise_()
        self.titler3.raise_()
        self.genrer3.raise_()
        self.label_17.raise_()
        self.frame_60.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.tabWidget.addTab(self.Actiontab, "")
        self.Randomtab = QtWidgets.QWidget()
        self.Randomtab.setObjectName("Randomtab")
        self.pushButton_9 = QtWidgets.QPushButton(self.Randomtab)
        self.pushButton_9.setGeometry(QtCore.QRect(30, 550, 32, 32))
        self.pushButton_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_9.setAutoFillBackground(False)
        self.pushButton_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_9.setText("")
        self.pushButton_9.setIcon(icon1)
        self.pushButton_9.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_9.setAutoExclusive(False)
        self.pushButton_9.setAutoDefault(False)
        self.pushButton_9.setDefault(False)
        self.pushButton_9.setFlat(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.frame_61 = QtWidgets.QFrame(self.Randomtab)
        self.frame_61.setGeometry(QtCore.QRect(157, 460, 51, 31))
        self.frame_61.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(255, 172, 7);\n"
"")
        self.frame_61.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_61.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_61.setObjectName("frame_61")
        self.rating4_5 = QtWidgets.QLabel(self.frame_61)
        self.rating4_5.setGeometry(QtCore.QRect(5, 4, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.rating4_5.setFont(font)
        self.rating4_5.setText("")
        self.rating4_5.setAlignment(QtCore.Qt.AlignCenter)
        self.rating4_5.setObjectName("rating4_5")
        self.frame_62 = QtWidgets.QFrame(self.Randomtab)
        self.frame_62.setGeometry(QtCore.QRect(157, 280, 51, 31))
        self.frame_62.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(255, 172, 7);\n"
"")
        self.frame_62.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_62.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_62.setObjectName("frame_62")
        self.rating_5 = QtWidgets.QLabel(self.frame_62)
        self.rating_5.setGeometry(QtCore.QRect(5, 4, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.rating_5.setFont(font)
        self.rating_5.setText("")
        self.rating_5.setAlignment(QtCore.Qt.AlignCenter)
        self.rating_5.setObjectName("rating_5")
        self.frame_63 = QtWidgets.QFrame(self.Randomtab)
        self.frame_63.setGeometry(QtCore.QRect(507, 280, 51, 31))
        self.frame_63.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(255, 172, 7);\n"
"")
        self.frame_63.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_63.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_63.setObjectName("frame_63")
        self.rating2_5 = QtWidgets.QLabel(self.frame_63)
        self.rating2_5.setGeometry(QtCore.QRect(5, 4, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.rating2_5.setFont(font)
        self.rating2_5.setText("")
        self.rating2_5.setAlignment(QtCore.Qt.AlignCenter)
        self.rating2_5.setObjectName("rating2_5")
        self.titler_2 = QtWidgets.QLabel(self.Randomtab)
        self.titler_2.setGeometry(QtCore.QRect(20, 410, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.titler_2.setFont(font)
        self.titler_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.titler_2.setText("")
        self.titler_2.setObjectName("titler_2")
        self.frame_64 = QtWidgets.QFrame(self.Randomtab)
        self.frame_64.setGeometry(QtCore.QRect(507, 460, 51, 31))
        self.frame_64.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(255, 172, 7);\n"
"")
        self.frame_64.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_64.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_64.setObjectName("frame_64")
        self.rating5_5 = QtWidgets.QLabel(self.frame_64)
        self.rating5_5.setGeometry(QtCore.QRect(5, 4, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.rating5_5.setFont(font)
        self.rating5_5.setText("")
        self.rating5_5.setAlignment(QtCore.Qt.AlignCenter)
        self.rating5_5.setObjectName("rating5_5")
        self.label_18 = QtWidgets.QLabel(self.Randomtab)
        self.label_18.setGeometry(QtCore.QRect(20, 300, 321, 111))
        self.label_18.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("Captura de ecrã 2020-05-28, às 11.18.43.png"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.genrer5_2 = QtWidgets.QLabel(self.Randomtab)
        self.genrer5_2.setGeometry(QtCore.QRect(370, 610, 321, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.genrer5_2.setFont(font)
        self.genrer5_2.setStyleSheet("color: rgb(107, 134, 153);")
        self.genrer5_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.genrer5_2.setText("")
        self.genrer5_2.setObjectName("genrer5_2")
        self.titler4_2 = QtWidgets.QLabel(self.Randomtab)
        self.titler4_2.setGeometry(QtCore.QRect(20, 590, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.titler4_2.setFont(font)
        self.titler4_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.titler4_2.setText("")
        self.titler4_2.setObjectName("titler4_2")
        self.label_19 = QtWidgets.QLabel(self.Randomtab)
        self.label_19.setGeometry(QtCore.QRect(720, 300, 321, 111))
        self.label_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("Captura de ecrã 2020-05-28, às 11.18.43.png"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.pushButton_10 = QtWidgets.QPushButton(self.Randomtab)
        self.pushButton_10.setGeometry(QtCore.QRect(30, 370, 32, 32))
        self.pushButton_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_10.setAutoFillBackground(False)
        self.pushButton_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_10.setText("")
        self.pushButton_10.setIcon(icon1)
        self.pushButton_10.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_10.setAutoExclusive(False)
        self.pushButton_10.setAutoDefault(False)
        self.pushButton_10.setDefault(False)
        self.pushButton_10.setFlat(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_20 = QtWidgets.QLabel(self.Randomtab)
        self.label_20.setGeometry(QtCore.QRect(370, 480, 321, 111))
        self.label_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("Captura de ecrã 2020-05-28, às 11.18.43.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.genrer2_2 = QtWidgets.QLabel(self.Randomtab)
        self.genrer2_2.setGeometry(QtCore.QRect(370, 430, 321, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.genrer2_2.setFont(font)
        self.genrer2_2.setStyleSheet("color: rgb(107, 134, 153);")
        self.genrer2_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.genrer2_2.setText("")
        self.genrer2_2.setObjectName("genrer2_2")
        self.genrer3_2 = QtWidgets.QLabel(self.Randomtab)
        self.genrer3_2.setGeometry(QtCore.QRect(720, 430, 321, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.genrer3_2.setFont(font)
        self.genrer3_2.setStyleSheet("color: rgb(107, 134, 153);")
        self.genrer3_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.genrer3_2.setText("")
        self.genrer3_2.setObjectName("genrer3_2")
        self.frame_65 = QtWidgets.QFrame(self.Randomtab)
        self.frame_65.setGeometry(QtCore.QRect(857, 280, 51, 31))
        self.frame_65.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(255, 172, 7);\n"
"")
        self.frame_65.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_65.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_65.setObjectName("frame_65")
        self.rating3_5 = QtWidgets.QLabel(self.frame_65)
        self.rating3_5.setGeometry(QtCore.QRect(5, 4, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.rating3_5.setFont(font)
        self.rating3_5.setText("")
        self.rating3_5.setAlignment(QtCore.Qt.AlignCenter)
        self.rating3_5.setObjectName("rating3_5")
        self.titler3_2 = QtWidgets.QLabel(self.Randomtab)
        self.titler3_2.setGeometry(QtCore.QRect(720, 410, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.titler3_2.setFont(font)
        self.titler3_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.titler3_2.setText("")
        self.titler3_2.setObjectName("titler3_2")
        self.pushButton_11 = QtWidgets.QPushButton(self.Randomtab)
        self.pushButton_11.setGeometry(QtCore.QRect(380, 550, 32, 32))
        self.pushButton_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_11.setAutoFillBackground(False)
        self.pushButton_11.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_11.setText("")
        self.pushButton_11.setIcon(icon1)
        self.pushButton_11.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_11.setAutoExclusive(False)
        self.pushButton_11.setAutoDefault(False)
        self.pushButton_11.setDefault(False)
        self.pushButton_11.setFlat(True)
        self.pushButton_11.setObjectName("pushButton_11")
        self.genrer4_2 = QtWidgets.QLabel(self.Randomtab)
        self.genrer4_2.setGeometry(QtCore.QRect(20, 610, 321, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.genrer4_2.setFont(font)
        self.genrer4_2.setStyleSheet("color: rgb(107, 134, 153);")
        self.genrer4_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.genrer4_2.setText("")
        self.genrer4_2.setObjectName("genrer4_2")
        self.label_21 = QtWidgets.QLabel(self.Randomtab)
        self.label_21.setGeometry(QtCore.QRect(370, 300, 321, 111))
        self.label_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("Captura de ecrã 2020-05-28, às 11.18.43.png"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.pushButton_12 = QtWidgets.QPushButton(self.Randomtab)
        self.pushButton_12.setGeometry(QtCore.QRect(380, 370, 32, 32))
        self.pushButton_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_12.setAutoFillBackground(False)
        self.pushButton_12.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_12.setText("")
        self.pushButton_12.setIcon(icon1)
        self.pushButton_12.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_12.setAutoExclusive(False)
        self.pushButton_12.setAutoDefault(False)
        self.pushButton_12.setDefault(False)
        self.pushButton_12.setFlat(True)
        self.pushButton_12.setObjectName("pushButton_12")
        self.titler5_2 = QtWidgets.QLabel(self.Randomtab)
        self.titler5_2.setGeometry(QtCore.QRect(370, 590, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.titler5_2.setFont(font)
        self.titler5_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.titler5_2.setText("")
        self.titler5_2.setObjectName("titler5_2")
        self.titler2_2 = QtWidgets.QLabel(self.Randomtab)
        self.titler2_2.setGeometry(QtCore.QRect(370, 410, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.titler2_2.setFont(font)
        self.titler2_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.titler2_2.setText("")
        self.titler2_2.setObjectName("titler2_2")
        self.label_22 = QtWidgets.QLabel(self.Randomtab)
        self.label_22.setGeometry(QtCore.QRect(20, 480, 321, 111))
        self.label_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("Captura de ecrã 2020-05-28, às 11.18.43.png"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.Genresbar = QtWidgets.QComboBox(self.Randomtab)
        self.Genresbar.setGeometry(QtCore.QRect(40, 100, 451, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.Genresbar.setFont(font)
        self.Genresbar.setEditable(True)
        self.Genresbar.setObjectName("Genresbar")
        self.Random = QtWidgets.QLabel(self.Randomtab)
        self.Random.setGeometry(QtCore.QRect(30, 220, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Random.setFont(font)
        self.Random.setObjectName("Random")
        self.pushButton_13 = QtWidgets.QPushButton(self.Randomtab)
        self.pushButton_13.setGeometry(QtCore.QRect(730, 370, 32, 32))
        self.pushButton_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_13.setAutoFillBackground(False)
        self.pushButton_13.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_13.setText("")
        self.pushButton_13.setIcon(icon1)
        self.pushButton_13.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_13.setAutoExclusive(False)
        self.pushButton_13.setAutoDefault(False)
        self.pushButton_13.setDefault(False)
        self.pushButton_13.setFlat(True)
        self.pushButton_13.setObjectName("pushButton_13")
        self.genrer_2 = QtWidgets.QLabel(self.Randomtab)
        self.genrer_2.setGeometry(QtCore.QRect(20, 430, 321, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.genrer_2.setFont(font)
        self.genrer_2.setStyleSheet("color: rgb(107, 134, 153);")
        self.genrer_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.genrer_2.setText("")
        self.genrer_2.setObjectName("genrer_2")
        self.pushButton_14 = QtWidgets.QPushButton(self.Randomtab)
        self.pushButton_14.setGeometry(QtCore.QRect(490, 100, 81, 41))
        self.pushButton_14.setDefault(False)
        self.pushButton_14.setFlat(False)
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_16 = QtWidgets.QPushButton(self.Randomtab)
        self.pushButton_16.setGeometry(QtCore.QRect(30, 550, 32, 32))
        self.pushButton_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_16.setAutoFillBackground(False)
        self.pushButton_16.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_16.setText("")
        self.pushButton_16.setIcon(icon1)
        self.pushButton_16.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_16.setAutoExclusive(False)
        self.pushButton_16.setAutoDefault(False)
        self.pushButton_16.setDefault(False)
        self.pushButton_16.setFlat(True)
        self.pushButton_16.setObjectName("pushButton_16")
        self.label_23 = QtWidgets.QLabel(self.Randomtab)
        self.label_23.setGeometry(QtCore.QRect(770, 30, 241, 221))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("../../../Downloads/image (2).png"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.pushButton_9.raise_()
        self.titler_2.raise_()
        self.label_18.raise_()
        self.genrer5_2.raise_()
        self.titler4_2.raise_()
        self.label_19.raise_()
        self.pushButton_10.raise_()
        self.label_20.raise_()
        self.genrer2_2.raise_()
        self.genrer3_2.raise_()
        self.frame_65.raise_()
        self.titler3_2.raise_()
        self.pushButton_11.raise_()
        self.genrer4_2.raise_()
        self.label_21.raise_()
        self.pushButton_12.raise_()
        self.titler5_2.raise_()
        self.titler2_2.raise_()
        self.label_22.raise_()
        self.Genresbar.raise_()
        self.Random.raise_()
        self.pushButton_13.raise_()
        self.genrer_2.raise_()
        self.pushButton_14.raise_()
        self.frame_62.raise_()
        self.frame_61.raise_()
        self.frame_63.raise_()
        self.frame_64.raise_()
        self.pushButton_16.raise_()
        self.label_23.raise_()
        self.tabWidget.addTab(self.Randomtab, "")
        self.Aboutab = QtWidgets.QWidget()
        self.Aboutab.setObjectName("Aboutab")
        self.label = QtWidgets.QLabel(self.Aboutab)
        self.label.setGeometry(QtCore.QRect(200, 60, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.Aboutab)
        self.label_2.setGeometry(QtCore.QRect(200, 90, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.Aboutab)
        self.label_4.setGeometry(QtCore.QRect(200, 110, 171, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.Aboutab)
        self.label_5.setGeometry(QtCore.QRect(60, 190, 111, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.textBrowser = QtWidgets.QTextBrowser(self.Aboutab)
        self.textBrowser.setGeometry(QtCore.QRect(80, 220, 231, 101))
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setObjectName("textBrowser")
        self.label_13 = QtWidgets.QLabel(self.Aboutab)
        self.label_13.setGeometry(QtCore.QRect(130, 60, 51, 61))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("../../../Downloads/logo_free-file.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_24 = QtWidgets.QLabel(self.Aboutab)
        self.label_24.setGeometry(QtCore.QRect(930, 430, 261, 331))
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap("../../../Downloads/logo_free-file.png"))
        self.label_24.setScaledContents(True)
        self.label_24.setWordWrap(False)
        self.label_24.setObjectName("label_24")
        self.tabWidget.addTab(self.Aboutab, "")
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.context)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #saving the title of the movies inside of combobox
        movt=movies["title"].dropna()
        movies_titles = movt.values.tolist()
        #saving the genre of movies
        genres=["Action","Adventure","Animation","Children's","Comedy",
                "Crime","Documentary","Drama","Fantasy","Film-Noir",
                "Horror","Musical","Mystery","Romance","Sci-Fi",
                 "Thriller", "War", "Western"]

        #saving the selected movie from combobox
        self.Movies.addItems(movies_titles)
        #saving the selected genre from the QComboBox
        self.Genresbar.addItems(genres)
        #creating and buttons
        def home_page():
            self.tabWidget.setCurrentIndex(0)

        def action_page():
            self.tabWidget.setCurrentIndex(1)

        def discover_page():
            self.tabWidget.setCurrentIndex(2)

        def about_page():
            self.tabWidget.setCurrentIndex(3)


        #adding items
        def adding_items():
            self.listWidget.clear()

            item=self.Movies.currentText()
            lista=recommendations.print_similar_movies(item)
            self.listWidget.addItems(recommendations.your_movie(item)[0:2])
            self.listWidget.addItem(str("{}{:.1f}".format("Rating: ",recommendations.your_movie(item)[2])))
            #titles
            self.titler.setText(lista[0][0])
            self.titler2.setText(lista[1][0])
            self.titler3.setText(lista[2][0])
            self.titler4.setText(lista[3][0])
            self.titler5.setText(lista[4][0])
            self.genrer.setText(lista[0][1])
            self.genrer2.setText(lista[1][1])
            self.genrer3.setText(lista[2][1])
            self.genrer4.setText(lista[3][1])
            self.genrer5.setText(lista[4][1])
            self.rating.setText(str("{:.1f}".format(lista[0][2])))
            self.rating2.setText(str("{:.1f}".format(lista[1][2])))
            self.rating3.setText(str("{:.1f}".format(lista[2][2])))
            self.rating4.setText(str("{:.1f}".format(lista[3][2])))
            self.rating5.setText(str("{:.1f}".format(lista[4][2])))

        def addding_items2():
            genre=self.Genresbar.currentText()
            rouList=recommendations.randomize(genre)
            self.titler_2.setText(rouList[0][0])
            self.titler2_2.setText(rouList[1][0])
            self.titler3_2.setText(rouList[2][0])
            self.titler4_2.setText(rouList[3][0])
            self.titler5_2.setText(rouList[4][0])
            self.genrer_2.setText(rouList[0][1])
            self.genrer2_2.setText(rouList[1][1])
            self.genrer3_2.setText(rouList[2][1])
            self.genrer4_2.setText(rouList[3][1])
            self.genrer5_2.setText(rouList[4][1])
            self.rating_5.setText(str("{:.1f}".format(rouList[0][2])))
            self.rating2_5.setText(str("{:.1f}".format(rouList[1][2])))
            self.rating3_5.setText(str("{:.1f}".format(rouList[2][2])))
            self.rating4_5.setText(str("{:.1f}".format(rouList[3][2])))
            self.rating5_5.setText(str("{:.1f}".format(rouList[4][2])))

        self.pushButton.clicked.connect(home_page)#link between home button and homepage
        self.pushButton_2.clicked.connect(action_page)#link between Movies button and moviepage
        self.pushButton_3.clicked.connect(adding_items)#Enter button from moviespage linked to additems fuction
        self.About.clicked.connect(about_page)#link between about button and aboutpage
        self.pushButton_15.clicked.connect(discover_page)#link between discover button and discoverpage
        self.pushButton_14.clicked.connect(addding_items2)#enter button for discoverpager linked to additem2 fuction

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MovieFlix"))
        self.searchbar.setText(_translate("MainWindow", "        Search movies"))
        self.label_3.setText(_translate("MainWindow", "MovieFlix"))
        self.label_66.setText(_translate("MainWindow", "Most Popular"))
        self.label_67.setText(_translate("MainWindow", "Crime, Horror, Thriller"))
        self.label_68.setText(_translate("MainWindow", "Crime, Drama"))
        self.label_69.setText(_translate("MainWindow", "The Silence of the Lambs"))
        self.label_70.setText(_translate("MainWindow", "The Matrix"))
        self.label_71.setText(_translate("MainWindow", "Comedy, Crime, Drama, Thriller"))
        self.label_72.setText(_translate("MainWindow", "Action, Sci-Fi, Thriller"))
        self.label_73.setText(_translate("MainWindow", "Forrest Gump"))
        self.label_74.setText(_translate("MainWindow", "Comedy, Drama, Romance, War"))
        self.label_75.setText(_translate("MainWindow", "4.2"))
        self.label_76.setText(_translate("MainWindow", "Pulp Fiction"))
        self.label_77.setText(_translate("MainWindow", "The Shawshank Redemption"))
        self.label_78.setText(_translate("MainWindow", "4.2"))
        self.label_79.setText(_translate("MainWindow", "4.2"))
        self.label_80.setText(_translate("MainWindow", "4.1"))
        self.label_81.setText(_translate("MainWindow", "4.4"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Home), _translate("MainWindow", "Tab 1"))
        self.Movies.setCurrentText(_translate("MainWindow", "Choose a movie..."))
        self.Recomendation.setText(_translate("MainWindow", "Your movie"))
        self.pushButton_3.setText(_translate("MainWindow", "Enter"))
        self.Recomendation_2.setText(_translate("MainWindow", "Recommendations"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Actiontab), _translate("MainWindow", "Tab 2"))
        self.Genresbar.setCurrentText(_translate("MainWindow", "Choose a genre..."))
        self.Random.setText(_translate("MainWindow", "Movie Roulette"))
        self.pushButton_14.setText(_translate("MainWindow", "Enter"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Randomtab), _translate("MainWindow", "Page"))
        self.label.setText(_translate("MainWindow", "MovieFlix"))
        self.label_2.setText(_translate("MainWindow", "v0.7 (64-bit)"))
        self.label_4.setText(_translate("MainWindow", "Project 3, 2020 Wild Code School"))
        self.label_5.setText(_translate("MainWindow", "Creators:"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://www.linkedin.com/in/georgerosa/\"><span style=\" font-size:8pt; text-decoration: underline; color:#ffffff;\">George Rosa-Acosta</span></a></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://www.linkedin.com/in/margarida-jervis/\"><span style=\" font-size:8pt; text-decoration: underline; color:#ffffff;\">Margarida Jervis</span></a></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://www.linkedin.com/in/nelson-rabasquinho-aa9b681a9/\"><span style=\" font-size:8pt; text-decoration: underline; color:#ffffff;\">Nelson Rabasquinho</span></a></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://www.linkedin.com/in/ugogallo/\"><span style=\" font-size:8pt; text-decoration: underline; color:#ffffff;\">Ugo Gallo</span></a></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Aboutab), _translate("MainWindow", "Page"))
import file_rc_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
